[build]
NIXPACKS_INSTALL_CMD = "npm install"
NIXPACKS_BUILD_CMD = "npm run deploy:build"

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
RAILWAY_DOCKERFILE_PATH = "Dockerfile"

[variables]
NODE_ENV = "production"
PORT = "4000"
SUPABASE_URL = "https://ijpwrspomqdnxavpjbzh.supabase.co"
SUPABASE_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqcHdyc3BvbXFkbnhhdnBqYnpoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczODM0Njc3NiwiZXhwIjoyMDUzOTIyNzc2fQ.9qjf-8uWdN6t1wS5i7BXI1Zp6lv-b0mcxXDaUJXFhTM"
DATABASE_URL = "${{Postgres.DATABASE_URL}}"
REDIS_URL = "${{Redis.REDIS_URL}}"
API_URL = "https://api-viralizamos.up.railway.app"
APP_URL = "https://loja.viralizamos.com.br"
AUTH_SECRET = "51gxLz40m3pW3r6KQ879aFVzmYqnWdDm"
QUEUE_PROVIDER = "redis"
PAYMENT_PROVIDER = "mercadopago"
MERCADOPAGO_ACCESS_TOKEN = "APP_USR-2980696238108733-061616-0bc76e1ee955da2daa8c6eb570f30f1a-111530251"
ACCESS_TOKEN_SECRET = "zF0LdXylBBiSA0MKrbaTDHPTiXy0OhKsLTUNTe7j8qYFh3G4FXB5QQA6nrWmvXG8"
REFRESH_TOKEN_SECRET = "9yUxQKtm2aQUHEQA1gYwbzQGFKfP72Z7JJw5B4mFmKcSKMsJqAcqnKtymKh9a41k"
CLIENT_APP_URL = "https://app.viralizamos.com.br"
API_KEY = "vrlzms_api_3ac5b8def47921e6a8b459f45d3c7a2fedcb1284"
ORDER_PROCESSING_QUEUE = "order-processing-queue"
QUEUE_PROCESSING_INTERVAL = "60000"
QUEUE_MAX_RETRY_ATTEMPTS = "3"
QUEUE_BACKOFF_DELAY = "5000"
QUEUE_CONCURRENCY = "3"
NEXTAUTH_URL = "https://orders.viralizamos.com"
NEXTAUTH_SECRET = "orders-development-secret-key"
NEXT_PUBLIC_APP_URL = "https://orders.viralizamos.com"
JWT_SECRET = "6bVERz8A5P4drqmYjN2ZxK$Fw9sXhC7uJtH3GeQpT!vLWkS#D@"
ORDERS_API_KEY = "vrlzms_api_3ac5b8def47921e6a8b459f45d3c7a2fedcb1284"
PAYMENTS_SERVICE_URL = "https://pagamentos.viralizamos.com"
PAYMENTS_API_KEY = "6bVERz8A5P4drqmYjN2ZxK$Fw9sXhC7uJtH3GeQpT!vLWkS#D@_payments"
PROVIDERS_API_BASE_URL = "https://api.provedores.viralizamos.com"
PROVIDERS_API_KEY = "vrlzms_providers_api_8a2c5e9b1d76f3g4h5i6j7k8l9m0n1o2"
MONITORING_API_KEY = "6bVERz8A5P4drqmYjN2ZxK$Fw9sXhC7uJtH3GeQpT!vLWkS#D@_monitoring"
LOG_LEVEL = "info"
ENABLE_REQUEST_LOGGING = "true"
REQUEST_TIMEOUT = "30000"
RATE_LIMIT_MAX = "100"
RATE_LIMIT_WINDOW_MS = "60000"
WEBHOOK_SECRET = "8f7a6b5c4d3e2f1g0h9i8j7k6l5m4n3o2p1q0r"
WEBHOOK_URL = "https://orders.viralizamos.com/api/webhooks" 